name: .NET (Host test)

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish (linux-x64)
        run: dotnet publish ./get-video.sln -c Release -r linux-x64 --self-contained false -o publish

      - name: Upload publish to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 62.171.188.96
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          source: "publish/*"
          target: "/opt/get-video/hosttest"
          overwrite: true

      - name: Run app on port 8081 (temporary)
        uses: appleboy/ssh-action@master
        with:
          host: 62.171.188.96
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            set -euo pipefail

            # old test process kill (if exists)
            pkill -f "/opt/get-video/hosttest/Web.dll" || true

            # run in background
            nohup /opt/dotnet/dotnet /opt/get-video/hosttest/Web.dll \
              --urls http://0.0.0.0:8081 \
              > /opt/get-video/hosttest/hosttest.log 2>&1 &

            sleep 2
            curl -I http://127.0.0.1:8081/ | head -n 20
